<?php
    $this->headTitle('登录');
?>

<?php
    if ($this->error) {
        echo '<p class="text-red">', $this->error, '</p>';
    }
?>
<form method="POST">
    <div class="mar-btm">
        <label class="inline-block w100 text-rgt">E-mail:</label>
        <input type="text" name="email" class="w200">
    </div>
    <div class="mar-btm">
        <label class="inline-block w100 text-rgt">密码:</label>
        <input type="password" name="password" class="w200">
    </div>
    <button type="submit">登录</button>
</form>
