<?php
    $this->headTitle('登录');
?>

<form class="form-horizontal mw400 margin-center" method="POST">
    <?php if ($this->error): ?>
    <div class="form-group">
        <div class="col-xs-offset-3 col-xs-9 text-danger">
            <?php echo $this->error; ?>
        </div>
    </div>
    <?php endif; ?>
    <div class="form-group">
        <label class="col-xs-3 control-label">E-mail:</label>
        <div class="col-xs-9">
            <input type="email" name="email" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-3 control-label">密码:</label>
        <div class="col-xs-9">
            <input type="password" name="password" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <div class="text-center">
            <button type="submit" class="btn btn-primary w100">登录</button>
        </div>
    </div>
</form>
