<?php
    $this->headTitle('编辑');
?>

<div class="margin-center mw1500">
    <form method="POST" class="mar-hor-lg">
        <?php
            if ($this->error) {
                echo '<div class="form-group text-danger">', $this->error, '</div>';
            }

            echo $this->formHidden('id', $this->post->id);
        ?>
        <div class="form-group mw400">
            <?php echo $this->categoryList($this->post->category); ?>
        </div>
        <div class="form-group">
            <?php
                echo $this->formText('title', $this->post->title, array(
                    'class'       => 'form-control',
                    'placeholder' => '文章标题'
                ));
            ?>
        </div>
        <?php if ($this->post->external_post): ?>
        <div class="form-group">
            <label>外部文章</label>
            <?php
                echo $this->formText('content', $this->post->content, array(
                    'class'       => 'form-control',
                    'placeholder' => '外部文章链接'
                ));
            ?>
        </div>
        <?php else: ?>
        <div id="editormd">
            <textarea name="content" class="hide"><?php echo $this->escape($this->post->content); ?></textarea>
        </div>
        <?php endif; ?>
        <div class="form-group">
            <?php
                $tags = Zend_Db_Table_Abstract::getDefaultAdapter()->fetchAll(
                    'SELECT t.name FROM post_tag pt, tag t WHERE pt.post_id = ' . $this->post->id . ' AND pt.tag_id = t.id ORDER BY pt.id ASC',
                    array(),
                    Zend_Db::FETCH_COLUMN
                );
                $tags = implode(',', $tags);

                echo $this->formText('tags', $tags, array(
                    'class'       => 'form-control',
                    'placeholder' => '标签'
                ));
            ?>
            <p class="help-block">多个标签使用,号分隔,最多可打10个标签</p>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary w100">提交</button>
        </div>
    </form>
</div>

<?php
    if (!$this->post->external_post) {
        $this->headLink()->appendStylesheet('/editormd/editormd.min.css')
                         ->appendStylesheet('/editormd/editormd.preview.overwrite.css');
        $this->headScript()->appendFile('/editormd/editormd.min.js')
                           ->appendFile('/js/admin/edit.js');
    }
?>
