<?php
    $this->headTitle('后台首页');
?>

<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Total: <?php echo $this->paginator->getTotalItemCount(); ?></td>
                <td width="100"></td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->paginator as $item): ?>
            <tr>
                <th><?php echo $this->escape($item['title']); ?></th>
                <td>
                    <a href="/admin/edit/?id=<?php echo $item['id']; ?>">编辑</a>
                    <a href="/admin/delete/?id=<?php echo $item['id']; ?>">删除</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->paginator; ?>
</div>
