
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headTitle('OurBlog')->setSeparator(' - '); ?>
    <?php echo $this->headLink(); ?>
    <link href="/style.css" rel="stylesheet">
</head>
<body>
    <div class="margin-center max-width-1200">
        <h1 class="border-btm text-lft">OurBlog</h1>
        <?php echo $this->layout()->content; ?>
    </div>
    <?php echo $this->headScript(); ?>
</body>
</html>
