
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headTitle('OurBlog')->setSeparator(' - '); ?>
    <?php echo $this->headLink(); ?>
    <link href="/css/style.css" rel="stylesheet">
</head>
<body>
    <div class="margin-center max-width-1200">
        <h1 class="border-btm text-lft">
            <a href="/" class="no-underline mar-rgt-lg">OurBlog</a>
            <a href="/" class="text-sm mar-rgt">首页</a>
            <?php
                $rows = Zend_Db_Table_Abstract::getDefaultAdapter()->fetchAll('SELECT id, name FROM category', array(), Zend_Db::FETCH_OBJ);
                foreach ($rows as $row) {
                    echo '<a href="/?category=', $row->id, '" class="text-sm mar-rgt">', htmlspecialchars($row->name), '</a>';
                }
            ?>
        </h1>

        <?php echo $this->layout()->content; ?>

    </div>

    <script src="/js/jquery-3.0.0.min.js"></script>
    <?php echo $this->headScript(); ?>
</body>
</html>
