
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headTitle('OurBlog')->setSeparator(' - '); ?>
    <link rel="stylesheet" href="/bootstrap/3.3.5/css/bootstrap.min.css">
    <link href="/css/style.css" rel="stylesheet">
    <?php echo $this->headLink(); ?>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <ul class="nav navbar-nav">
                <li<?php echo $this->category ? '' : ' class="active"'; ?>>
                    <a class="navbar-brand" href="/">Home</a>
                </li>
                <?php
                    $rows = Zend_Db_Table_Abstract::getDefaultAdapter()->fetchAll('SELECT id, name FROM category', array(), Zend_Db::FETCH_OBJ);
                    foreach ($rows as $row) {
                        echo '<li', ($this->category == $row->id ? ' class="active"' : ''), '>',
                                '<a href="/?category=', $row->id, '">',
                                    $this->escape($row->name),
                                '</a>',
                             '</li>';
                    }
                ?>
            </ul>
        </div>
    </nav>

    <div class="container">
        <?php echo $this->layout()->content; ?>
    </div>

    <script src="/js/jquery-3.0.0.min.js"></script>
    <script src="/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <?php echo $this->headScript(); ?>
</body>
</html>
